# -*- coding: utf-8 -*-
"""projeto5_g7_f.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZP7KaAWZ9hNW2IjXyiFcwUE_OsQtZe2a

# Projeto SR1 - Análise de Dados Orçamentários

Este notebook Colab segue o roteiro da Avaliação Técnica SR1 para a **Compreensão do Conjunto de Dados**, focando nas etapas de descrição, limpeza, contextualização e análise inicial.

## 1. Configuração e Carregamento dos Dados
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import numpy as np
import seaborn as sns

# Importando arquivo do github.
url = 'https://raw.githubusercontent.com/GuigaGibson/projeto5-colab/main/bancotsefinal.xlsx'

try:

  df = pd.read_excel(url)
  print("Arquivo carregado com sucesso diretamente do GitHub!")

except Exception as e:
  print(f"Ocorreu um erro ao tentar carregar o arquivo: {e}")

cidades = {
    "P093": "Limoeiro",
    "P098": "Moreno",
    "P110": "Paudalho"
}

"""##  Descrição Inicial e Diagnóstico do Dataset

**Descrição do dataset** (tamanho e estrutura) e **Compreensão das variáveis** (tipos de dados), este bloco verifica a integridade e a estrutura inicial do DataFrame. O diagnóstico dos nomes das colunas é crucial para a limpeza subsequente.
"""

# Tamanho Dataset
print(f"O DataFrame foi carregado com sucesso. Ele possui {df.shape[0]} linhas e {df.shape[1]} colunas.")

#Tipos de dados iniciais (antes da limpeza)
print("\nTipos de dados iniciais das colunas:")
print(df.info())

#Primeiras linhas para visualização da estrutura
print("\nPrimeiras 5 linhas do DataFrame para visualização:")
display(df.head()) # 'display' é melhor para o Colab/Jupyter

#Verificando os nomes originais (saída da leitura do arquivo)
print("\nNomes das colunas originais (para diagnóstico):\n", df.columns.tolist())

# Numero de linhas e colunas
num_linhas, num_colunas = df.shape
print(f"Número de linhas: {num_linhas}")
print(f"Número de colunas (variáveis): {num_colunas}")

# Tamanho total
tamanho_total = df.size
print(f"Tamanho total do dataset (células): {tamanho_total}")

"""### Conclusão da Análise Inicial de Tipos de Dados (Seção 2)

O DataFrame possui 21.804 registros e 36 colunas. A análise inicial revela:

1.  **Variáveis Categóricas/Textuais (Object):** A maioria das colunas (22) é do tipo `object`, o que inclui identificadores (como `CODIGO_MUNICIPIO`, `CPF_CNPJ`), descrições (como `ACAO`, `FUNCAO`, `FORNECEDOR`) e as colunas com prefixos problemáticos (e.g., `resposta.conteudo.`).
2.  **Variáveis Numéricas:**
    * **Inteiras (`int64`):** Variáveis como ano (`ANOREFERENCIA`, `Ano`) e códigos de identificação (`ID_EMPENHO`, `CODIGO_TIPO_ACAO`).
    * **Flutuantes (`float64`):** As colunas de valor (e.g., `VALOREMPENHADO`, `VALORPAGO`) e alguns códigos que foram lidos como agregados (`Soma de...`) estão como `float64`, o que é ideal para os valores monetários.
3.  **Variáveis Temporais:** A coluna de data (`DATAEMPENHO` original) está ausente. Algumas variáveis temporais, como `Mês` (Object) e `MESREFERENCIA` (Float), precisarão ser padronizadas ou combinadas para análises temporais.

A próxima etapa (**Seção 3**) será dedicada à limpeza desses nomes e à garantia de que os tipos numéricos e de data estejam corretos.

# Limpeza Inicial, Padronização e Conversão de Tipos

**ATENÇÃO: Esta é apenas uma Limpeza Inicial para Habilitar a Análise Exploratória.**

Nesta etapa, o foco é a **padronização dos nomes das colunas** e a **conversão de tipos de dados** essenciais:
* **Valores:** Colunas financeiras (`VALOREMPENHADO`, etc.) são convertidas de texto formatado (ex: vírgula/ponto) para o tipo numérico (`float64`).

Uma fase posterior será dedicada à Limpeza e Tratamento de Dados mais complexos (como imputação de valores faltantes, tratamento de *outliers* e padronização de variáveis categóricas).
"""

# --- 1. Limpeza e Padronização de Colunas ---

# Converter para string, remover espaços extras e forçar maiúsculas (para consistência)
df.columns = df.columns.astype(str).str.strip().str.upper()

# remover os prefixos e padronizar
def limpar_nome_coluna(nome):
    # Remove os prefixos problemáticos. Não usa 'regex=False' pois é str.replace nativo.
    nome = nome.replace('SOMA DE ', '')
    nome = nome.replace('RESPOSTA.CONTEUDO.', '')

    # Substitui espaços e pontos por underscores para facilitar o acesso
    nome = nome.replace(' ', '_').replace('.', '_')

    # Remove underscores extras no início/fim
    return nome.strip('_')

# Aplica a limpeza
df.columns = [limpar_nome_coluna(col) for col in df.columns]

print("Nomes das colunas limpos e padronizados com sucesso.")
print("Novos nomes das colunas:\n", df.columns.tolist())


# --- 2. Conversão de Tipos de Dados ---

# A lista usa os nomes limpos e padronizados
colunas_valor = ['VALORLIQUIDADO', 'VALORPAGO', 'VALOREMPENHADO']

# Conversão e Preenchimento para colunas de valor
for col in colunas_valor:
    if col in df.columns:
        # Lógica robusta para tratar números formatados com separador de milhares (ponto) e decimal (vírgula)
        try:
            # 1. Remove o separador de milhares (ponto)
            # 2. Substitui a vírgula pelo ponto (separador decimal do Python)
            df[col] = df[col].astype(str).str.replace('.', '', regex=False).str.replace(',', '.', regex=False)

            # 3. Converte para numérico
            df[col] = pd.to_numeric(df[col], errors='coerce')
        except Exception as e:
            # Fallback simples em caso de erro na conversão
            df[col] = pd.to_numeric(df[col], errors='coerce')
    else:
        print(f"AVISO: Coluna de valor '{col}' não encontrada no DataFrame após a limpeza.")

# Preenche valores faltantes nas colunas numéricas com 0
df[colunas_valor] = df[colunas_valor].fillna(0)
print("Colunas de valor convertidas para numérico e preenchidas com 0.")


# Conversão de Coluna de Data
coluna_data = 'DATAEMPENHO'
if coluna_data in df.columns:
    df[coluna_data] = pd.to_datetime(df[coluna_data], errors='coerce')
    print(f"Coluna de data '{coluna_data}' convertida para datetime.")
else:
    print(f"AVISO: Coluna de data '{coluna_data}' não encontrada no DataFrame.")

print("\nVerificação dos tipos de dados após a limpeza:")
df.info()

"""### Conclusão da Análise Inicial de Tipos de Dados e Variáveis

O DataFrame consolidado possui 21.804 registros e 36 colunas. A análise inicial revela:

1.  **Tipos de Dados:** A maioria das colunas descritivas está corretamente tipada como `object` (textual). As colunas de valor (e.g., `VALORPAGO`, `VALOREMPENHADO`) foram lidas como `float64`, o que é apropriado para a fase exploratória. A coluna de data de empenho (`DATAEMPENHO`) está ausente no dataset.
2.  **Variáveis Categóricas Chave:**
    * A coluna **`FUNCAO`**, crucial para a análise, contém unicamente  a categoria **'EDUCAÇÃO'**, pois ja foi fatiada pelo proprio API do TCE-PE
    * As colunas de código de município (`CODIGO_MUNICIPIO`) permitem a segmentação pelos três municípios de interesse.

A próxima etapa  é a limpeza inicial dos nomes, corte de periodo e a conversão final de tipos para garantir a integridade dos dados para análise.

## 2. Limpeza dos Dados

Esta fase inicia o **Tratamento de Inconsistências** e a **Padronização** necessárias para a análise, conforme o slide "Limpeza dos Dados".

Inicialmente sera feita um recorte do periodo entre 2022-2024. Para melhorar a analise do trabalho.
"""

# --- 1. FILTRO TEMPORAL (Restrição de Uso) ---
# Ações: Eliminar linhas que não sejam dos anos 2022, 2023, 2024.
anos_interesse = [2022, 2023, 2024]
coluna_ano_ref = 'ANOREFERENCIA'

if coluna_ano_ref in df.columns:
    df_antes = df.shape[0]
    # Filtra as linhas onde o ANOREFERENCIA está na lista de anos de interesse
    df = df[df[coluna_ano_ref].isin(anos_interesse)].copy()
    df_depois = df.shape[0]

    print(f"Filtro aplicado: Dados restritos aos anos {anos_interesse}.")
    print(f"Linhas removidas: {df_antes - df_depois} (Restantes: {df_depois} linhas).")
else:
    print(f"AVISO: Coluna de ano '{coluna_ano_ref}' não encontrada. O filtro não foi aplicado.")

"""### 2.2 Tratamento de Inconsistências (Nomes de Coluna e Tipos de Dados)

Os passos a seguir focam na padronização de nomes (Tratamento de Inconsistências) e na conversão de colunas de valor (Correção de Erros Evidentes / Padronização de Formatos) para preparar o dataset para a análise numérica.
"""

# PADRONIZAÇÃO DE NOMES (Tratamento de Inconsistências - Nomes) ---

df.columns = df.columns.astype(str).str.strip().str.upper()

def limpar_nome_coluna(nome):
    # Remove prefixos problemáticos
    nome = nome.replace('SOMA DE ', '').replace('RESPOSTA.CONTEUDO.', '')
    # Padroniza nomes de colunas de resposta
    nome = nome.replace('RESPOSTA.ENTIDADE', 'RESPOSTA_ENTIDADE').replace('.', '_')
    # Substitui espaços e pontos restantes por underscores
    nome = nome.replace(' ', '_').replace('.', '_')
    return nome.strip('_')

df.columns = [limpar_nome_coluna(col) for col in df.columns]

print("Nomes das colunas limpos e padronizados com sucesso.")


# EXCLUSÃO DE COLUNAS NÃO ESSENCIAIS (Redução de Dimensionalidade) ---
colunas_para_remover = [
    'CODIGO_TIPO_EMPENHO',
    'ELEMENTODESPESA',
    'ESFERA',
    'ID_UNIDADE_GESTORA',
    'ID_EMPENHO',
    'NATUREZA',
    'NUMEROEMPENHO',
    'RESPOSTA_ENTIDADE',
    'RESPOSTA_LIMITERESULTADO',
    'RESPOSTA_STATUS',
    'RESPOSTA_TAMANHORESULTADO'
]

colunas_existentes = [col for col in colunas_para_remover if col in df.columns]

if colunas_existentes:
    df = df.drop(columns=colunas_existentes)
    print(f"Colunas removidas com sucesso: {colunas_existentes}")
else:
    print("AVISO: Nenhuma das colunas especificadas foi encontrada para remoção.")


print("\n--- LISTA FINAL DE COLUNAS APÓS LIMPEZA E EXCLUSÃO ---")
# Exibe a lista completa de nomes de colunas padronizados
print(df.columns.tolist())
print(f"Total de colunas restantes: {len(df.columns)}")

# 2. Distribuição por CIDADE (Variável Mapeada - Se Existente)
if 'CIDADE' in df.columns:
    print("Distribuição e Quantidade das recorrências por NOME DA CIDADE:")
    # O .value_counts() lista e conta, e o .head(4) limita aos 4 mais frequentes.
    print(df['CIDADE'].value_counts().head(3))
else:
    print("AVISO: A coluna 'CIDADE' (com os nomes Limoeiro, Moreno, Paudalho) não foi encontrada no DataFrame. ")
    print("Ela é geralmente criada por mapeamento do CODIGO_MUNICIPIO.")

"""### 2.3 Padronização de Formatos e Tratamento de Ausentes

Esta etapa final de limpeza foca na conversão de tipos (garantindo que colunas financeiras sejam numéricas) e no **tratamento de valores ausentes** nas colunas de valor, antes da fase exploratória.
"""

#--- Conversão segura das colunas de valor ---
colunas_valor = ['VALORLIQUIDADO', 'VALORPAGO', 'VALOREMPENHADO']

for col in colunas_valor:
    if col in df.columns:
        try:
            # Remove apenas vírgula decimal (não mexe em ponto se já for separador correto)
            df[col] = (
                df[col]
                .astype(str)
                .str.replace('\xa0', '', regex=False)  # remove espaços não quebráveis
                .str.replace(',', '.', regex=False)    # vírgula decimal → ponto
                .str.replace('[^0-9.]', '', regex=True)  # mantém só números e ponto
            )

            # Converte para float de forma segura
            df[col] = pd.to_numeric(df[col], errors='coerce')

        except Exception as e:
            print(f"Erro ao converter {col}: {e}")

#Substitui ausentes por 0
df[colunas_valor] = df[colunas_valor].fillna(0)
print("✅ Colunas de valor convertidas corretamente para numérico e preenchidas com 0.")

# Conversão de Data (tentativa de padronização)
coluna_data = 'DATAEMPENHO'
if coluna_data in df.columns:
    df[coluna_data] = pd.to_datetime(df[coluna_data], errors='coerce')
    print(f"Coluna de data '{coluna_data}' convertida para datetime.")
else:
    print(f"AVISO: Coluna de data '{coluna_data}' não encontrada no DataFrame.")


condicao_negativos = (df[colunas_valor] < 0).any(axis=1)
qtd_negativos = condicao_negativos.sum()

if qtd_negativos > 0:
    print(f"⚠️ {qtd_negativos} registros com valores negativos detectados. Removendo do DataFrame...")
    df = df[~condicao_negativos].copy()
else:
    print("✅ Nenhum valor negativo encontrado nas colunas monetárias.")

print("\n--- Verificação final dos tipos de dados após limpeza ---")
df.info()
print("\nVerificação final dos tipos de dados após a limpeza:")
df.info()

"""Analisando a forma de escrita das categorias de subfuncao"""

# Garante que a coluna 'FUNCAO' seja tratada como texto
df['FUNCAO'] = df['FUNCAO'].astype(str).str.strip()
df['SUBFUNCAO'] = df['SUBFUNCAO'].astype(str).str.strip()


print("--- Categorias Únicas na Coluna 'FUNCAO' ---")
# O comando .unique() cria uma lista com cada nome de função que aparece no arquivo, sem repetições.
funcoes_unicas = df['FUNCAO'].unique()
print(funcoes_unicas)

print("\n\n--- Contagem de Registros por 'FUNCAO' (As 15 mais comuns) ---")
contagem_funcoes = df['FUNCAO'].value_counts()
print(contagem_funcoes.head(15))


print("\n\n--- Contagem de Registros por 'SUBFUNCAO' (As 20 mais comuns) ---")
contagem_subfuncoes = df['SUBFUNCAO'].value_counts()
print(contagem_subfuncoes.head(20))

# Gera uma lista Python com todos os nomes únicos da coluna
lista_de_funcoes = df['FUNCAO'].unique().tolist()
print(lista_de_funcoes)
lista_de_funcoes = df['SUBFUNCAO'].unique().tolist()
print(lista_de_funcoes)

df['CODIGO_MUNICIPIO'] = df['CODIGO_MUNICIPIO'].astype(str).str.strip()

# 2. Cria a coluna 'CIDADE' aplicando o mapeamento
# Se a coluna 'CIDADE' já existir, ela será sobrescrita.
df['CIDADE'] = df['CODIGO_MUNICIPIO'].apply(lambda cod: cidades.get(cod, 'Outras/Não Identificada'))

# 3. Confirmação do sucesso
print("Mapeamento das cidades (P093, P098, P110) concluído com sucesso.")
print("A coluna 'CIDADE' foi criada no DataFrame principal ('df').")

# Verificação (opcional)
print("\nPrimeiros 5 registros de MUNICÍPIO e CIDADE para conferência:")
display(df[['CODIGO_MUNICIPIO', 'CIDADE']].head())

"""## Faremos a correcao a partir de um dicionario, para substituicao de caracteres indevidos"""

# Mapearemos a palavra errada para a palavra correta
mapa_de_correcao = {

    'Educa��o': 'EDUCAÇÃO',

    'Educa��o de Jovens e Adultos': 'EDUCAÇÃO DE JOVENS E ADULTOS',
    'Servi�o da D�vida Interna': 'SERVIÇO DA DÍVIDA INTERNA',
    'Ensino Fundamental': 'ENSINO FUNDAMENTAL',
    'Ensino Superior': 'ENSINO SUPERIOR',
    'Administra��o Geral': 'ADMINISTRAÇÃO GERAL',
    'Educa��o Infantil': 'EDUCAÇÃO INFANTIL',
    'Alimenta��o e Nutri��o': 'ALIMENTAÇÃO E NUTRIÇÃO',
    'Educa��o B�sica': 'EDUCAÇÃO BÁSICA',

    'Difus�o Cultural': 'DIFUSÃO CULTURAL',
    'Educa��o Especial': 'EDUCAÇÃO ESPECIAL',
    'Forma��o de Recursos Humanos': 'FORMAÇÃO DE RECURSOS HUMANOS'

}

colunas_para_corrigir = ['FUNCAO', 'SUBFUNCAO', 'PROGRAMA', 'NOMEUNIDADEGESTORA', 'FORNECEDOR', 'HISTORICO']

for coluna in colunas_para_corrigir:
    if coluna in df.columns: # Apenas se a coluna existir
        df[coluna] = df[coluna].replace(mapa_de_correcao)

print("✅ Correção manual aplicada!")


# Verificacao final
print("\n--- Verificação FINAL da coluna 'FUNCAO' ---")
print(df['FUNCAO'].value_counts().head(20))

print("\n--- Verificação FINAL da coluna 'SUBFUNCAO' ---")
print(df['SUBFUNCAO'].value_counts().head(30))

"""Feita a limpeza agora inicia-se a analise preliminar

## 3. Análise Preliminar

Esta fase é dedicada à **Análise Preliminar**, focando na obtenção de **Estatísticas descritivas** (médias, medianas, desvios) e na **Exploração de correlações** e **padrões iniciais** (tendências e variações). O objetivo é gerar **insights iniciais** sobre a distribuição dos recursos da função 'EDUCAÇÃO' por município.

### 3.1 Estatísticas Descritivas e Agregação por Município e Ano

Serão calculadas estatísticas descritivas para a variável `VALORPAGO`, agrupadas pela combinação de `CIDADE` e `ANOREFERENCIA`.
"""

# --- REVERSÃO E NOVA TRANSFORMAÇÃO GLOBAL E PERMANENTE ---
coluna_valor = 'VALORPAGO'
coluna_cidade = 'CIDADE'
funcao_alvo = 'EDUCAÇÃO'


# 2. Aplica a nova transformação: divide todos os valores da coluna VALORPAGO por 1000 no DF PRINCIPAL
df[coluna_valor] = df[coluna_valor] / 1000

print(f"VALORPAGO no DF completo após a divisão por 1000 (Exemplo): {df[coluna_valor].head().to_string(index=False)}")
print("\nAVISO CRÍTICO: O DataFrame original 'df' foi reajustado e PERMANENTEMENTE modificado. Todos os valores de VALORPAGO são agora 1000 vezes menores.")

# --- INÍCIO DA ANÁLISE (Estatísticas Descritivas) ---

# 3. Filtra apenas os registros da função EDUCAÇÃO (agora com valores já divididos por 1000)
df_educacao = df[df['FUNCAO'] == funcao_alvo].copy()

if df_educacao.empty:
    print(f"\nAVISO: Nenhum registro encontrado para FUNÇÃO='{funcao_alvo}'.")
else:

    print(f"\n--- ESTATÍSTICAS DESCRITIVAS ATUALIZADAS (FUNÇÃO: {funcao_alvo}) POR CIDADE ---")

    # 4. Usa .describe() para gerar estatísticas por cidade
    df_descritivas = (
        df_educacao.groupby(coluna_cidade)[coluna_valor]
        .describe(percentiles=[0.25, 0.5, 0.75])
        .reset_index()
    )

    # 5. Renomeia colunas para português
    df_descritivas = df_descritivas.rename(columns={
        'count': 'Contagem',
        'mean': 'Média',
        'std': 'Desvio_Padrão',
        'min': 'Mínimo',
        '25%': '1º Quartil (25%)',
        '50%': 'Mediana (50%)',
        '75%': '3º Quartil (75%)',
        'max': 'Máximo'
    })

    # 6. Formata valores monetários (R$ X.XXX,XX)
    for col in ['Média', 'Desvio_Padrão', 'Mínimo', '1º Quartil (25%)',
                'Mediana (50%)', '3º Quartil (75%)', 'Máximo']:
        df_descritivas[col] = df_descritivas[col].apply(lambda x: f'R$ {x:,.2f}' if pd.notnull(x) else '-')

    display(df_descritivas)

    # 7. Mostrar a soma total por cidade
    print("\n--- TOTAL GASTO EM EDUCAÇÃO POR CIDADE (SOMA DE TODOS OS ANOS) ---")
    df_soma = (
        df_educacao.groupby(coluna_cidade)[coluna_valor]
        .sum()
        .reset_index()
        .rename(columns={coluna_valor: 'Total_Gasto'})
        .sort_values(by='Total_Gasto', ascending=False)
    )

    # Formatação R$ X.XXX.XXX,XX (Valor total na nova escala, dividida por 1000)
    df_soma['Total_Gasto'] = df_soma['Total_Gasto'].apply(lambda x: f'R$ {x:,.2f}')
    display(df_soma)



"""### 3.2 Exploração de Padrões e Discussão de Insights Iniciais

O foco é na **Exploração de correlações** e na **Identificação de padrões iniciais**, usando os gastos agregados para analisar a **evolução e variação temporal** entre os municípios.
"""

# --- EXPLORAÇÃO DE CORRELAÇÕES E IDENTIFICAÇÃO DE PADRÕES INICIAIS ---
# Usando os gastos agregados para analisar a evolução e variação temporal entre os municípios.

# --- Pré-requisito: Gasto Total Anual por Cidade (Necessário para a Variação) ---
coluna_valor = 'VALORPAGO'
colunas_agrupamento = ['CIDADE', 'ANOREFERENCIA']
funcao_alvo = 'EDUCAÇÃO'

# Filtra apenas a função de interesse
df_analise = df[df['FUNCAO'] == funcao_alvo].copy()

# Agregação do gasto total anual (BASE NUMÉRICA)
df_gastos_agregados = (
    df_analise
    .groupby(colunas_agrupamento)[coluna_valor]
    .sum()
    .reset_index()
)

# Criação da tabela pivô (CIDADE x ANO)
tabela_numerica = df_gastos_agregados.pivot_table(
    index='CIDADE',
    columns='ANOREFERENCIA',
    values=coluna_valor,
    aggfunc='sum'
)

# --- Análise de Variação Percentual (Exploração de correlações / padrões) ---
print("--- ANÁLISE DE VARIAÇÃO PERCENTUAL DE GASTO ANUAL (2022-2024) ---")

# Cálculo da variação percentual ano a ano
variacao_22_23 = (
    (tabela_numerica.get(2023, 0) - tabela_numerica.get(2022, 0))
    / tabela_numerica.get(2022, np.nan)
)

variacao_23_24 = (
    (tabela_numerica.get(2024, 0) - tabela_numerica.get(2023, 0))
    / tabela_numerica.get(2023, np.nan)
)

# Consolida as variações em um único DataFrame
df_variacao = pd.concat([
    variacao_22_23.rename('VARIAÇÃO_2022_2023'),
    variacao_23_24.rename('VARIAÇÃO_2023_2024')
], axis=1)

# Substitui infinitos e NaN por valores nulos antes da formatação
df_variacao = df_variacao.replace([np.inf, -np.inf], np.nan)

# Formata a saída em porcentagem para clareza visual
df_variacao_formatada = df_variacao.map(
    lambda x: f'{x:.1%}' if pd.notna(x) and not np.isinf(x) else 'N/A'
)

# Exibe a tabela formatada
display(df_variacao_formatada)

"""--- DISCUSSÃO DE INSIGHTS INICIAIS (INTERPRETAÇÃO DOS PADRÕES) ---
1. Outliers e Dispersão: A diferença entre média e mediana (ver bloco 3.1) sugere que poucos registros de alto valor elevam o gasto médio, indicando a presença de outliers.
2. Padrão de Evolução: Variações positivas indicam crescimento do gasto entre os anos. Já valores negativos, como observado em Moreno (2023–2024), representam retração orçamentária ou execução parcial do recurso.
3. Concentração de Gasto: A cidade com maior gasto absoluto (do bloco 3.1) deve ser comparada à contagem de transações, para avaliar se o gasto está distribuído ou concentrado em poucos contratos.
4. Correlação Temporal: Municípios com crescimento consistente sugerem maior estabilidade financeira ou maior eficiência na execução orçamentária.

### 3.3 Análise e Exploração das Variáveis Categóricas e Numéricas

Nesta etapa da análise exploratória, buscou-se compreender como as variáveis categóricas — como **CIDADE, ANOREFERENCIA e SUBFUNCAO**   — se relacionam com a variável numérica principal **VALORPAGO**, que representa o montante efetivamente desembolsado na função Educação.

O objetivo foi identificar padrões de comportamento orçamentário e diferenças estruturais entre os municípios e suas áreas de atuação, verificando como o valor pago varia conforme o contexto institucional e funcional.

####  Distribuição do Gasto por Município

A partir dessa análise, observou-se que o **VALORPAGO** apresenta distribuições distintas entre as categorias, refletindo o porte e a capacidade de execução orçamentária de cada município:

* Em **Paudalho**, os valores são mais elevados e dispersos, indicando maior amplitude de contratos e diversidade de despesas.
* Em **Moreno**, a concentração em faixas médias sugere estabilidade e foco em custeio recorrente.
* Já em **Limoeiro**, há menor dispersão e predominância de pagamentos uniformes, sinalizando execução mais controlada e previsível.

####  Impacto das Subfunções

Entre as subfunções, destaca-se a forte predominância do **Ensino Fundamental**, responsável pela maior parcela dos valores pagos, seguida por Educação Infantil e Alimentação Escolar, com proporções significativamente menores. Essa distribuição reforça o caráter estruturalmente concentrado do gasto educacional municipal, direcionado majoritariamente à manutenção do ensino básico.

####  Padrões Temporais e Estruturais

A análise cruzada também permitiu identificar padrões temporais — com **crescimento gradual dos valores pagos entre 2022 e 2024** — e diferenças de intensidade entre as categorias de município, evidenciando a influência de fatores como capacidade fiscal, priorização política e estrutura administrativa.

Em síntese, a interação entre as variáveis categóricas e numéricas revela **heterogeneidade de comportamento orçamentário**, mas **homogeneidade na estrutura de gasto**, demonstrando que, embora os valores variem, a lógica de aplicação permanece concentrada nas despesas de pessoal e manutenção do ensino regular.

## 4. Processo de Visualização

Esta fase é dedicada à **Visualização de Dados**, utilizando gráficos para reforçar os *insights* obtidos na Análise Preliminar (Sessão 3).

### 4.1 Visualização Univariada: Gasto Total Consolidado por Cidade

O gráfico de barras é a **Escolha adequada de gráficos** para comparar o volume absoluto de `VALORPAGO` entre as três cidades no período total (2022-2024).
"""

# --- Pré-requisito: Agregação do Gasto Total (2022-2024) ---
coluna_valor = 'VALORPAGO'
funcao_alvo = 'EDUCAÇÃO'

# 1. Filtra apenas os registros da função EDUCAÇÃO
df_educacao = df[df['FUNCAO'] == funcao_alvo].copy()

# 2. Calcula a soma total do VALORPAGO, agrupada apenas por CIDADE
df_gasto_total = (
    df_educacao.groupby('CIDADE')[coluna_valor]
    .sum()
    .reset_index()
    .rename(columns={coluna_valor: 'Gasto_Total_Consolidado'})
    # Ordena pelo gasto decrescente (do maior para o menor)
    .sort_values(by='Gasto_Total_Consolidado', ascending=False)
)

# --- Geração do Gráfico de Barras Horizontal ---
plt.figure(figsize=(10, 6))

# CORES PERSONALIZADAS: Azul (#3055a0), Amarelo (#fab331), Vermelho (#bc4a49)
cores_personalizadas = ['#3055a0', '#fab331', '#bc4a49']

ax = sns.barplot(
    data=df_gasto_total,
    x='Gasto_Total_Consolidado',
    y='CIDADE',
    palette=cores_personalizadas,
    orient='h'
)

# Formatação do Eixo X em Milhões de R$ (Clareza visual)
def millions_formatter(x, pos):
    return f'R$ {x/1000000:,.1f}M'
formatter = mtick.FuncFormatter(millions_formatter)
plt.gca().xaxis.set_major_formatter(formatter)


# --- Adição dos Rótulos de Valor DENTRO da Caixa (Cor Branca para Contraste) ---
for container in ax.containers:
    for bar in container:
        width = bar.get_width()
        label_text = f'R$ {width/1000000:,.2f}M'

        # Posição X ligeiramente à direita do início da barra (dentro dela)
        ax.text(
            width * 0.02,
            bar.get_y() + bar.get_height() / 2,
            label_text,
            ha='left',
            va='center',
            fontsize=11,
            color='white', # Mantendo cor branca para contraste com as novas cores
            weight='bold'
        )

plt.title(f'Gasto Total Consolidado (2022-2024) em {funcao_alvo} por Município', fontsize=16, weight='bold')
plt.xlabel('Valor Pago Total (R$ Milhões)', fontsize=12)
plt.ylabel('Cidade', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""### 4.2 Boxplot para Distribuição de Gastos e Análise de Outliers

O Boxplot (gráfico de dispersão univariada) é utilizado para analisar a **distribuição das variáveis** de `VALORPAGO` por transação, por cidade. A escala logarítmica limitada (`< log 8`) permite uma visualização detalhada da densidade dos valores mais baixos, enquanto ainda mostra a presença de *outliers* de alto valor.
"""

# --- Pré-requisito: Filtro e Mapeamento ---
coluna_valor = 'VALORPAGO'
coluna_log = 'LOG10_VALOR'
funcao_alvo = 'EDUCAÇÃO'
cidades_interesse = ['Limoeiro', 'Moreno', 'Paudalho']

df_plot = df[(df['FUNCAO'] == funcao_alvo) & (df['CIDADE'].isin(cidades_interesse))].copy()

if df_plot.empty:
    print(f"\nAVISO: O DataFrame para plotagem (FUNCAO='{funcao_alvo}' nas cidades de interesse) está vazio.")
else:
    # 1. CRIAÇÃO DA NOVA COLUNA DE MÉTRICA
    # Aplica log10(1 + valor) para lidar com a compressão e valores zero.
    df_plot[coluna_log] = np.log10(1 + df_plot[coluna_valor])

    # --- Configurações do Boxplot ---
    cores_personalizadas = {
        'Paudalho': '#3055a0', # Azul
        'Moreno': '#fab331',   # Amarelo
        'Limoeiro': '#bc4a49'  # Vermelho
    }

    plt.figure(figsize=(8, 5))

    # 2. Geração do Boxplot na Nova Métrica
    sns.boxplot(
        data=df_plot,
        x=coluna_log, # Usamos a nova coluna transformada
        y='CIDADE',
        palette=cores_personalizadas,
        order=['Paudalho', 'Moreno', 'Limoeiro']
    )

    # 3. Formatação do Título e Eixos (Clareza visual)
    plt.title(
        'Distribuição Logarítmica dos Valores Pagos em Educação por Cidade',
        fontsize=14,
        weight='bold'
    )
    plt.xlabel('Log10(1 + Valor Pago)', fontsize=10)
    plt.ylabel('Cidade', fontsize=10)
    plt.grid(axis='x', linestyle='--', alpha=0.6)

    plt.tight_layout()
    plt.show()

    # --- Interpretação (Discussão de insights iniciais) ---
    print("\nINSIGHTS DO BOXPLOT COM TRANSFORMAÇÃO DE MÉTRICA:")
    print("1. Nova Mediana: A linha central (mediana) agora representa o logaritmo do valor típico pago, facilitando a comparação direta.")
    print("2. Visão de Dispersão: A amplitude das caixas e dos *whiskers* (hastes) mostra o quão espalhada está a distribuição dos valores logarítmicos.")

"""Devido a dificuldade de visualizacao utilizaremos o metodo de Violino.

"""

# --- Pré-requisito: Criação da Métrica Logarítmica ---
coluna_log = 'LOG10_VALOR'
funcao_alvo = 'EDUCAÇÃO'
cidades_interesse = ['Limoeiro', 'Moreno', 'Paudalho']

df_plot = df[(df['FUNCAO'] == funcao_alvo) & (df['CIDADE'].isin(cidades_interesse))].copy()

if df_plot.empty:
    print(f"\nAVISO: O DataFrame para plotagem (FUNCAO='{funcao_alvo}' nas cidades de interesse) está vazio.")
else:
    # Garante que a coluna logarítmica exista para a plotagem
    if coluna_log not in df_plot.columns:
        df_plot[coluna_log] = np.log10(1 + df_plot['VALORPAGO'])

    # --- Configurações do Gráfico de Violino ---
    cores_personalizadas = {
        'Paudalho': '#3055a0', # Azul
        'Moreno': '#fab331',   # Amarelo
        'Limoeiro': '#bc4a49'  # Vermelho
    }

    plt.figure(figsize=(8, 5))

    # 1. Geração do Gráfico de Violino (Violin Plot)
    sns.violinplot(
        data=df_plot,
        x=coluna_log,
        y='CIDADE',
        palette=cores_personalizadas,
        order=['Paudalho', 'Moreno', 'Limoeiro'],
        inner='quartile' # Mostra a mediana e os quartis dentro do violino
    )

    # 2. Formatação do Título e Eixos (Clareza visual)
    plt.title(
        'Distribuição da Densidade de Valores Pagos (Métrica Logarítmica)',
        fontsize=14,
        weight='bold'
    )
    plt.xlabel('Log10(1 + Valor Pago)', fontsize=10)
    plt.ylabel('Cidade', fontsize=10)
    plt.grid(axis='x', linestyle='--', alpha=0.6)

    plt.tight_layout()
    plt.show()

    # --- Interpretação (Discussão de insights iniciais) ---
    print("\nINSIGHTS DO GRÁFICO DE VIOLINO:")
    print("1. Densidade: O formato largo do 'corpo' do violino na extremidade esquerda (valores logarítmicos baixos) confirma a enorme concentração de transações de baixo valor.")
    print("2. Distribuição: O gráfico de violino mostra que, embora a mediana seja baixa, a distribuição de Moreno (Amarelo) é mais ampla em valores maiores que Limoeiro, indicando maior variabilidade de gastos.")

"""
O gráfico de violino reforça os padrões de distribuição e variabilidade dos gastos:

* **Concentração da Despesa:** O formato estreito do "corpo" dos violinos em valores logarítmicos baixos confirma que a **maioria esmagadora** das transações em Limoeiro, Moreno e Paudalho são de valores pequenos.
* **Diferença de Variabilidade (Moreno):** O violino de Moreno (Amarelo) é visivelmente mais largo e disperso em valores logarítmicos maiores. Isso indica uma **maior variabilidade** e frequência de transações de valores médios na cidade.
* **Limoeiro (Extrema Concentração):** Limoeiro (Vermelho) tem a distribuição mais concentrada e estreita, apontando para a **menor variabilidade** nos valores de pagamento.
* **Outliers Extremos:** As longas caudas em todas as cidades confirmam a presença de *outliers* de altíssimo valor, crucial para a etapa de **Correção de erros evidentes**.

###  Identificação de Limitações do Conjunto de Dados

Para cumprir o objetivo de medir a "evolução" de forma eficaz, o conjunto de dados apresenta as seguintes limitações:

1.  **Ausência de Variáveis de Contexto Financeiro:**
    * Não há dados sobre o **Orçamento Total** de cada município. A análise está limitada à comparação de valores absolutos (`VALORPAGO`) e não à **proporção** do gasto em Educação.
2.  **Ausência de Variáveis de Resultado:**
    * Não há métricas de eficiência ou resultado educacional (ex: IDEB). Isso impede que a "evolução" do gasto seja correlacionada com a **efetividade** da despesa.
3.  **Restrições de Uso:**
    * A análise se restringe a apenas **três municípios** e ao período **2022-2024**, limitando a generalização das conclusões.
4.  **Impacto dos Outliers:**
    * A alta dispersão do `VALORPAGO` (conforme visto no violino e no boxplot) indica que o *outlier* tem um impacto desproporcional na média, exigindo tratamento rigoroso em etapas futuras.

Estes pontos definem os limites da análise atual e indicam a necessidade de **incorporar dados externos** para aprofundamento em fases subsequentes."""

# --- Configurações básicas ---
coluna_valor = 'VALORPAGO'
colunas_agrupamento = ['CIDADE', 'ANOREFERENCIA']
funcao_alvo = 'EDUCAÇÃO'

# --- 1️⃣ Padronização dos valores monetários ---
if df[coluna_valor].dtype == 'object':
    df[coluna_valor] = (
        df[coluna_valor]
        .astype(str)
        .str.replace('\xa0', '', regex=False)          # remove espaços não quebráveis
        .str.replace('.', '', regex=False)             # remove pontos de milhar
        .str.replace(',', '.', regex=False)            # substitui vírgula decimal por ponto
        .str.replace('[^0-9\.]', '', regex=True)       # mantém só números e ponto
    )
    df[coluna_valor] = pd.to_numeric(df[coluna_valor], errors='coerce')

# Substitui valores ausentes por zero
df[coluna_valor] = df[coluna_valor].fillna(0)

# --- 2️⃣ Filtragem apenas para EDUCAÇÃO ---
df_educacao = df[df['FUNCAO'] == funcao_alvo].copy()

# --- 3️⃣ Agregação: soma total por cidade e ano ---
df_gasto_anual = (
    df_educacao
    .groupby(colunas_agrupamento)[coluna_valor]
    .sum()
    .reset_index()
)

# --- 4️⃣ Paleta de cores personalizada ---
cores_personalizadas = {
    'Paudalho': '#3055a0',  # azul
    'Limoeiro': '#bc4a49',  # vermelho
    'Moreno': '#fab331'     # amarelo
}

# --- 5️⃣ Criação do gráfico ---
plt.figure(figsize=(10, 6))
ax = sns.barplot(
    data=df_gasto_anual,
    x='ANOREFERENCIA',
    y=coluna_valor,
    hue='CIDADE',
    palette=cores_personalizadas
)

# --- 6️⃣ Formatação do eixo Y em milhões de reais ---
def millions_formatter(x, pos):
    return f'R$ {x/1_000_000:,.1f}M'
ax.yaxis.set_major_formatter(mtick.FuncFormatter(millions_formatter))

# --- 7️⃣ Rótulos dentro das barras, formatados verticalmente ---
for container in ax.containers:
    # Ajuste fino do valor vertical para centralizar dentro das barras
    ax.bar_label(
        container,
        labels=[f'R$ {v.get_height():,.0f}'.replace(',', 'X').replace('.', ',').replace('X', '.')
                for v in container],  # converte para padrão brasileiro
        label_type='center',
        fontsize=9,
        color='white',
        weight='bold',
        rotation=90,      # texto na vertical
        padding=2
    )

# --- 8️⃣ Ajustes visuais e título ---
plt.title('Gasto Anual em Educação por Município (2022–2024)', fontsize=15, weight='bold')
plt.xlabel('Ano de Referência', fontsize=12)
plt.ylabel('Valor Pago (R$ Milhões)', fontsize=12)
plt.legend(title='Município', fontsize=10)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""## Insight — Evolução do Gasto Anual em Educação (2022–2024)

O comportamento dos gastos públicos em Educação entre 2022 e 2024 evidencia um **crescimento consistente e contínuo** nos três municípios analisados — Paudalho, Limoeiro e Moreno —, com destaque para a expansão mais acelerada de Paudalho, que atinge o maior volume absoluto em 2024.

### Análise por Município

🔹 **Paudalho** apresenta uma trajetória de forte crescimento acumulado, passando de 65,9 milhões de reais em 2022 para 92,6 milhões de reais em 2024 — um aumento de aproximadamente 40% em dois anos. Esse avanço reflete expansão de programas educacionais, incremento de infraestrutura e aumento da folha de pessoal, além de possível execução ampliada de recursos vinculados à educação básica.

🔹 **Limoeiro** segue um padrão de crescimento estável e gradual, evoluindo de 54,2 milhões de reais para 70,2 milhões de reais, o que corresponde a um aumento de cerca de 30%. O município mantém ritmo de expansão contínuo, sugerindo planejamento progressivo e previsibilidade fiscal na execução orçamentária da função Educação.

🔹 **Moreno**, apesar de apresentar crescimento mais contido (de 54,7 milhões de reais para 60,2 milhões de reais, cerca de 10%), demonstra maior estabilidade, possivelmente associada a restrições de receita ou priorização de gastos correntes essenciais. Essa tendência pode indicar limitação de investimento em novas ações ou dependência de transferências externas.

### Padrão Consolidado

De forma agregada, o gráfico revela que, embora todos os municípios ampliem seus gastos educacionais, a intensidade desse crescimento é desigual, refletindo capacidades fiscais distintas e estratégias diferentes de alocação de recursos.

O destaque de Paudalho sinaliza maior esforço orçamentário por habitante, enquanto Moreno mantém o menor ritmo de expansão, o que pode impactar a capacidade de aprimorar infraestrutura e qualidade do ensino.
"""

# --- Parâmetros ---
coluna_valor = 'VALORPAGO'
coluna_categoria = 'SUBFUNCAO'
coluna_cidade = 'CIDADE'
funcao_alvo = 'EDUCAÇÃO'

# --- 1. Agregação dos dados ---
df_subfuncao = (
    df[df['FUNCAO'] == funcao_alvo]
    .groupby([coluna_cidade, coluna_categoria])[coluna_valor]
    .sum()
    .reset_index()
)

# Converte para milhões de reais para melhor escala
df_subfuncao[coluna_valor] = df_subfuncao[coluna_valor] / 1_000_000

# --- 2. Pivot para formato adequado (CIDADE x SUBFUNCAO) ---
df_pivot = df_subfuncao.pivot_table(
    index=coluna_cidade,
    columns=coluna_categoria,
    values=coluna_valor,
    fill_value=0
)

# --- 3. Plotagem ---
cores = sns.color_palette("Spectral", n_colors=len(df_pivot.columns))

ax = df_pivot.plot(
    kind='bar',
    stacked=True,
    figsize=(12, 6),
    color=cores,
    alpha=0.9,
    edgecolor='none'
)

# --- 4. Formatação e títulos ---
plt.title('Distribuição do Gasto em Educação por Subfunção e Cidade (2022–2024)', fontsize=15, weight='bold', pad=15)
plt.xlabel('Cidade', fontsize=12)
plt.ylabel('Valor Pago Total (em Milhões de R$)', fontsize=12)
plt.legend(title='Subfunção', bbox_to_anchor=(1.02, 1), loc='upper left', fontsize=9)
plt.grid(axis='y', linestyle='--', alpha=0.4)

# Formata eixo Y em R$ Milhões
ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f'R$ {x:,.1f}M'))

# --- 5. Rótulos de valor total por cidade ---
totais = df_pivot.sum(axis=1)
for i, total in enumerate(totais):
    ax.text(i, total + 5, f"R$ {total:.1f}M", ha='center', va='bottom', fontsize=10, fontweight='bold', color='black')

plt.tight_layout()
plt.show()

"""## Insight — Estrutura do Gasto Educacional por Subfunção (2022–2024)

A distribuição consolidada dos gastos em Educação entre os municípios de Limoeiro, Moreno e Paudalho revela uma estrutura orçamentária fortemente concentrada na subfunção **Ensino Fundamental**, que representa mais de 70% do total pago em todos os casos. Essa predominância indica o caráter estruturalmente rígido da despesa educacional, com foco majoritário em manutenção do ensino básico e folha de pessoal.

### Análise por Município

🔹 **Paudalho** lidera em volume absoluto, com aproximadamente R$ 232,9 milhões, resultado de uma expansão significativa nas subfunções Educação Infantil e Ensino Fundamental. Esse comportamento sugere maior intensidade de investimento e crescimento da rede pública, tanto em infraestrutura quanto em ampliação de vagas.

🔹 **Limoeiro**, com cerca de R$ 189,1 milhões, apresenta uma distribuição mais equilibrada, embora ainda concentrada no ensino fundamental. Nota-se leve aumento nas subfunções Educação Infantil e Alimentação e Nutrição, o que pode indicar reforço em políticas de apoio pedagógico e de inclusão escolar.

🔹 **Moreno**, por sua vez, exibe o menor volume consolidado (R$ 177,0 milhões) e menor diversificação funcional, com gastos majoritariamente vinculados à manutenção do ensino regular. O peso reduzido das subfunções complementares sugere restrições orçamentárias ou foco em custeio administrativo.

### Padrão Consolidado

De modo geral, o gráfico evidencia que o perfil de gasto educacional dos três municípios permanece altamente concentrado, com baixa variação funcional entre localidades. Essa homogeneidade reflete a dependência dos orçamentos municipais em despesas obrigatórias de pessoal e encargos, reduzindo o espaço fiscal para ações estruturantes e inovação pedagógica.
"""

# --- Parâmetros ---
coluna_valor = 'VALORPAGO'
colunas_agrupamento = ['CIDADE', 'ANOREFERENCIA', 'SUBFUNCAO']
funcao_alvo = 'EDUCAÇÃO'

# --- 1. Agregação dos dados ---
df_subfuncao_cidade = (
    df[df['FUNCAO'] == funcao_alvo]
    .groupby(colunas_agrupamento)[coluna_valor]
    .sum()
    .reset_index()
)

# Converte para milhões de reais
df_subfuncao_cidade[coluna_valor] = df_subfuncao_cidade[coluna_valor] / 1_000_000

# --- 2. Seleciona as Top 3 Subfunções Globais ---
top3_subfuncoes = (
    df_subfuncao_cidade.groupby('SUBFUNCAO')[coluna_valor]
    .sum()
    .sort_values(ascending=False)
    .head(3)
    .index
)

df_top3 = df_subfuncao_cidade[df_subfuncao_cidade['SUBFUNCAO'].isin(top3_subfuncoes)]

# --- 3. Criação do FacetGrid (um painel por cidade) ---
g = sns.FacetGrid(
    df_top3,
    col='CIDADE',
    hue='SUBFUNCAO',
    col_wrap=3,
    height=4,
    aspect=1.3,
    palette=['#3055a0', '#fab331', '#bc4a49']
)

# --- 4. Desenha as linhas e pontos ---
g.map(sns.lineplot, 'ANOREFERENCIA', coluna_valor, marker='o', linewidth=2.2)
g.map(sns.scatterplot, 'ANOREFERENCIA', coluna_valor, s=80, edgecolor='black', linewidth=0.5)

# --- 5. Adiciona rótulos de valor em cada ponto ---
for ax, (cidade, df_sub) in zip(g.axes.flatten(), df_top3.groupby('CIDADE')):
    for _, row in df_sub.iterrows():
        ax.text(
            row['ANOREFERENCIA'], row[coluna_valor] + 0.5,
            f"R$ {row[coluna_valor]:.1f}M",
            ha='center', va='bottom',
            fontsize=8.5, color='black', fontweight='bold'
        )

# --- 6. Formatação dos eixos e layout ---
for ax in g.axes.flatten():
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f'R$ {x:,.1f}M'))
    ax.grid(axis='y', linestyle='--', alpha=0.4)
    ax.set_xlabel('Ano de Referência')
    ax.set_ylabel('Valor Pago (em Milhões de R$)')

# --- 7. Ajustes globais ---
g.add_legend(title='Subfunção', fontsize=9)
plt.subplots_adjust(top=0.88)
g.fig.suptitle(
    'Evolução dos Gastos em Educação — Top 3 Subfunções por Cidade (2022–2024)',
    fontsize=15, fontweight='bold'
)
plt.show()

"""## Insight — Estrutura e Dinâmica do Gasto Educacional (2022–2024)

A análise integrada das subfunções e dos principais fornecedores da função Educação revela um quadro de alta concentração em despesas de pessoal e manutenção de ensino, com crescimento contínuo do gasto total e diferenciação significativa entre os municípios quanto à composição e prioridade orçamentária.

O gráfico evidencia que, em todos os municípios analisados, a subfunção **“Ensino Fundamental” domina amplamente a execução orçamentária**, representando o núcleo central do gasto educacional — variando entre 46 milhões de reais e 74 milhões de reais no período de 2022 a 2024. Essa trajetória ascendente reflete a rigidez estrutural do custeio educacional, associada principalmente à folha de pagamento e encargos previdenciários.

### Análise por Município

🔹 **Paudalho** apresenta o maior volume absoluto e crescimento mais acentuado, atingindo cerca de 74,8 milhões de reais em 2024, o que indica expansão de programas e possível ampliação do quadro funcional da rede municipal. O destaque para “Educação Infantil” — com salto de 6,8 milhões de reais para 11,9 milhões de reais — reforça um movimento de investimento na base da educação.

🔹 **Moreno** mantém um perfil de crescimento mais estável, com valores entre 51 milhões de reais e 59 milhões de reais no Ensino Fundamental. Entretanto, as subfunções “Educação Infantil” e “Alimentação e Nutrição” permanecem quase estagnadas, sugerindo baixa diversificação das políticas educacionais ou forte dependência de programas federais.

🔹 **Limoeiro**, embora parta de valores menores, revela crescimento contínuo e uma recomposição gradual da estrutura de gasto, com destaque para a “Educação Infantil” e a “Alimentação Escolar”, ambas em trajetória ascendente. Essa tendência sugere maior equilíbrio entre custeio e apoio pedagógico, ainda que o foco principal continue sendo o ensino básico.

### Padrão Estrutural Consolidado

De forma consolidada, os três municípios compartilham um mesmo padrão estrutural:

* Predominância da subfunção **Ensino Fundamental** como eixo central do orçamento;
* Baixa participação das subfunções complementares (alimentação e educação infantil);
* Crescimento nominal expressivo, mas com **concentração em despesas obrigatórias**.

Esse comportamento indica baixo grau de flexibilidade orçamentária e reforça a importância de aperfeiçoar a governança do gasto educacional, de modo a equilibrar a execução entre manutenção, infraestrutura e inovação pedagógica — elementos essenciais para a melhoria da qualidade do ensino e a eficiência do investimento público.
"""

# --- Parâmetros ---
coluna_valor = 'VALORPAGO'
colunas_agrupamento = ['CIDADE', 'ANOREFERENCIA', 'FORNECEDOR']
funcao_alvo = 'EDUCAÇÃO'

# --- 1. Filtra e agrega os dados ---
df_fornecedores = (
    df[df['FUNCAO'] == funcao_alvo]
    .groupby(colunas_agrupamento)[coluna_valor]
    .sum()
    .reset_index()
)

# Converte para milhões de reais
df_fornecedores[coluna_valor] = df_fornecedores[coluna_valor] / 1_000_000

# --- 2. Seleciona Top 5 fornecedores por cidade e ano ---
df_top5 = (
    df_fornecedores
    .sort_values(['CIDADE', 'ANOREFERENCIA', coluna_valor], ascending=[True, True, False])
    .groupby(['CIDADE', 'ANOREFERENCIA'])
    .head(5)
    .reset_index(drop=True)
)

# --- 3. Exibição estruturada por cidade e ano ---
print("===== TOP 5 FORNECEDORES POR CIDADE E ANO (EM MILHÕES DE R$) =====")
for (cidade, ano), grupo in df_top5.groupby(['CIDADE', 'ANOREFERENCIA']):
    print(f"\n📍 {cidade} — {ano}")
    display(
        grupo[['FORNECEDOR', coluna_valor]]
        .rename(columns={'FORNECEDOR': 'Fornecedor', coluna_valor: 'Valor Pago (R$ Milhões)'})
        .style.format({'Valor Pago (R$ Milhões)': 'R$ {:.2f}M'})
    )

# --- 4. (Opcional) Visualização gráfica resumida ---
plt.figure(figsize=(10, 6))
sns.barplot(
    data=df_top5,
    x=coluna_valor,
    y='FORNECEDOR',
    hue='CIDADE',
    orient='h',
    palette=['#3055a0', '#fab331', '#bc4a49']
)

plt.title('Top 5 Fornecedores em Educação (2022–2024)', fontsize=15, weight='bold')
plt.xlabel('Valor Pago (Milhões de R$)', fontsize=11)
plt.ylabel('Fornecedor', fontsize=11)
plt.legend(title='Cidade')
plt.grid(axis='x', linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

"""##Insight — Concentração e Padrões de Fornecimento na Função Educação (2022–2024)

A análise dos Top 5 fornecedores por cidade e ano evidencia um forte padrão de concentração orçamentária em torno da Folha de Pagamento e de órgãos previdenciários e educacionais municipais, reforçando o peso estrutural das despesas de pessoal e encargos na função Educação.

Em todos os municípios, a Folha de Pagamento ocupa a liderança absoluta dos gastos, representando a principal destinação orçamentária da educação — variando de cerca de R$ 30 a 48 milhões anuais, o que reflete a alta rigidez das despesas de custeio e o baixo espaço fiscal para investimentos diretos em infraestrutura ou inovação pedagógica.

🔹 Limoeiro demonstra um padrão de gasto crescente, com destaque para a Faculdade de Ciências da Administração e prestadores de serviços de apoio (como D. Feitosa Aluguel de Máquinas e Construtora Pilartex). Há indícios de diversificação de fornecedores ao longo dos anos, embora o componente de folha continue predominante.

🔹 Moreno apresenta maior continuidade contratual, com fornecedores recorrentes como SOLSERV Serviços Ltda. e Prime Consultoria e Assessoria Empresarial Ltda., além de expressiva participação da Folha de Pagamento, que supera R$ 40 milhões por ano. Essa estabilidade pode indicar contratos plurianuais ou terceirização de serviços continuados.

🔹 Paudalho, por sua vez, exibe forte correlação entre o Fundo Municipal de Educação e fornecedores locais (como Octagon Empreendimentos Ltda. e José Luiz Félix Cabral Júnior ME). A ampliação expressiva dos repasses ao Fundo Municipal de Educação em 2024 (R$ 17,1 milhões) sugere expansão de programas ou reestruturação financeira interna.

De forma geral, o período 2022–2024 confirma um cenário de centralização das despesas educacionais em compromissos obrigatórios de pessoal, com menor representatividade de contratos de natureza operacional ou inovadora. Essa configuração reforça a necessidade de análises complementares sobre a eficiência do gasto corrente e a dependência de fornecedores estratégicos, elementos centrais para a governança e o planejamento de médio prazo.

# **Separação limpeza 2**
"""

for i, col in enumerate(df.columns):
    print(i, col)

[x for x in df['ACAO'].unique() if "�" in str(x) or "?" in str(x)]

mapa_de_correcao_acao = {
    'ALFABETIZA��O DE JOVENS E ADULTOS 70%': 'ALFABETIZAÇÃO DE JOVENS E ADULTOS 70%',
    'AMORTIZA��O DA D�VIDA': 'AMORTIZAÇÃO DA DÍVIDA',
    'AMPLIA��O E RESTAURA��O DO PR�DIO DA FACAL': 'AMPLIAÇÃO E RESTAURAÇÃO DO PRÉDIO DA FACAL',
    'Aquisi??o de fardamento para estudantes': 'AQUISIÇÃO DE FARDAMENTO PARA ESTUDANTES',
    'Aquisi��o de fardamento para estudantes': 'AQUISIÇÃO DE FARDAMENTO PARA ESTUDANTES',
    'AQUISI��O DE TRANSPORTE ESCOLAR': 'AQUISIÇÃO DE TRANSPORTE ESCOLAR',
    'Aquisi��o de ve�culos destinados ao transporte de estudantes.': 'AQUISIÇÃO DE VEÍCULOS DESTINADOS AO TRANSPORTE DE ESTUDANTES',
    'Construir ampliar e equipar a??es do PAR - Plano de A??es Articuladas': 'CONSTRUIR, AMPLIAR E EQUIPAR AÇÕES DO PAR - PLANO DE AÇÕES ARTICULADAS',
    'CONSTRU��O AMPLIA��O E REFORMAS DE CRECHE': 'CONSTRUÇÃO, AMPLIAÇÃO E REFORMAS DE CRECHE',
    'CONSTRU��O AMPLIA��O E RESTAURA��O DE UNIDADES ESCOLARES E QUADRAS PO': 'CONSTRUÇÃO, AMPLIAÇÃO E RESTAURAÇÃO DE UNIDADES ESCOLARES E QUADRAS POLIESPORTIVAS',
    'Constru��o e/ou recupera��o de creches e escolas e aquisi��o de mobili': 'CONSTRUÇÃO E/OU RECUPERAÇÃO DE CRECHES E ESCOLAS E AQUISIÇÃO DE MOBILIÁRIO',
    'CONTRIBUI��ES PREVID�NCI�RIAS E FGTS': 'CONTRIBUIÇÕES PREVIDENCIÁRIAS E FGTS',
    'CONTRIBUI��O PARA O PASEP': 'CONTRIBUIÇÃO PARA O PASEP',
    'DESAPROPRIA��O': 'DESAPROPRIAÇÃO',
    'Desapropria��o de Im�veis para Educa��o do Munic�pio': 'DESAPROPRIAÇÃO DE IMÓVEIS PARA EDUCAÇÃO DO MUNICÍPIO',
    'Educa??o de Jovens e Adultos': 'EDUCAÇÃO DE JOVENS E ADULTOS',
    'Educa��o de Jovens e Adultos': 'EDUCAÇÃO DE JOVENS E ADULTOS',
    'Gest?o Administrativa da Educa??o Municipal': 'GESTÃO ADMINISTRATIVA DA EDUCAÇÃO MUNICIPAL',
    'Gest�o Administrativa da Educa��o Municipal': 'GESTÃO ADMINISTRATIVA DA EDUCAÇÃO MUNICIPAL',
    'GEST�O T�CNICA E ADMINISTRATIVA DA FACAL': 'GESTÃO TÉCNICA E ADMINISTRATIVA DA FACAL',
    'GEST�O T�CNICA E ADMINISTRATIVA DA SECRETARIA': 'GESTÃO TÉCNICA E ADMINISTRATIVA DA SECRETARIA',
    'Manuten??o do Ensino Fundamental': 'MANUTENÇÃO DO ENSINO FUNDAMENTAL',
    'Manuten??o do Ensino Infantil': 'MANUTENÇÃO DO ENSINO INFANTIL',
    'MANUTEN��O APOIADORES DA EDUCA��O': 'MANUTENÇÃO APOIADORES DA EDUCAÇÃO',
    'MANUTEN��O DA BIBLIOTECA': 'MANUTENÇÃO DA BIBLIOTECA',
    'MANUTEN��O DA EDUCA��O INFANTIL': 'MANUTENÇÃO DA EDUCAÇÃO INFANTIL',
    'MANUTEN��O DA EDUCA��O INFANTIL - NOVAS TURMAS': 'MANUTENÇÃO DA EDUCAÇÃO INFANTIL - NOVAS TURMAS',
    'MANUTEN��O DA EDUCA��O INFANTIL 70%': 'MANUTENÇÃO DA EDUCAÇÃO INFANTIL 70%',
    'MANUTEN��O DO ENSINO FUNDAMENTAL': 'MANUTENÇÃO DO ENSINO FUNDAMENTAL',
    'MANUTEN��O DO ENSINO FUNDAMENTAL 30%': 'MANUTENÇÃO DO ENSINO FUNDAMENTAL 30%',
    'MANUTEN��O DO ENSINO FUNDAMENTAL 70%': 'MANUTENÇÃO DO ENSINO FUNDAMENTAL 70%',
    'MANUTEN��O DO ENSINO FUNDAMENTAL/SAL�RIO EDUCA��O': 'MANUTENÇÃO DO ENSINO FUNDAMENTAL / SALÁRIO EDUCAÇÃO',
    'Manuten��o do Ensino Infantil': 'MANUTENÇÃO DO ENSINO INFANTIL',
    'MANUTEN��O DO ENSINO SUPERIOR': 'MANUTENÇÃO DO ENSINO SUPERIOR',
    'MANUTEN��O DO TRANSPORTE ESCOLAR': 'MANUTENÇÃO DO TRANSPORTE ESCOLAR',
    'MANUTEN��O DO TRANSPORTE ESCOLAR 30%': 'MANUTENÇÃO DO TRANSPORTE ESCOLAR 30%',
    'Oferecer servi?o de transporte aos estudantes univesit?rios morenenses': 'OFERECER SERVIÇO DE TRANSPORTE AOS ESTUDANTES UNIVERSITÁRIOS MORENENSES',
    'Oferecer servi?o de transporte escolar regular para os alunos de escol': 'OFERECER SERVIÇO DE TRANSPORTE ESCOLAR REGULAR PARA OS ALUNOS DE ESCOLAS MUNICIPAIS',
    'Oferecer servi�o de transporte aos estudantes universit�rios morenense': 'OFERECER SERVIÇO DE TRANSPORTE AOS ESTUDANTES UNIVERSITÁRIOS MORENENSES',
    'Oferecer servi�o de transporte escolar regular para os alunos de escol': 'OFERECER SERVIÇO DE TRANSPORTE ESCOLAR REGULAR PARA OS ALUNOS DE ESCOLAS MUNICIPAIS',
    'PROGRAMA DE ALIMENTA��O ESCOLAR': 'PROGRAMA DE ALIMENTAÇÃO ESCOLAR',
    'REEQUIPAMENTO DA EDUCA��O INFANTIL': 'REEQUIPAMENTO DA EDUCAÇÃO INFANTIL',
    'REEQUIPAMENTO DO ENSINO FUNDAMENTAL E AQUISA��O DE VE�CULOS': 'REEQUIPAMENTO DO ENSINO FUNDAMENTAL E AQUISIÇÃO DE VEÍCULOS',
    'REEQUIPAMENTO DO ENSINO FUNDAMENTAL E AQUISI��O DE VE�CULOS': 'REEQUIPAMENTO DO ENSINO FUNDAMENTAL E AQUISIÇÃO DE VEÍCULOS'
}


df['ACAO'] = df['ACAO'].replace(mapa_de_correcao_acao)

df['ACAO'].unique()

df['FORNECEDOR'].unique()

mapa_fornecedor = {
    'Folha de Pagamento (Fornecedor Padr�o)': 'FOLHA DE PAGAMENTO (FORNECEDOR PADRÃO)',
    'VENEZA DIESEL CAMINH�ES �NIBUS LTDA': 'VENEZA DIESEL CAMINHÕES ÔNIBUS LTDA',
    'FNDE - FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCA��O': 'FNDE - FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCAÇÃO',
    'ASSOCIA��O PEQUENOS PRODUTORES RURAIS ENGENHO JUSSARA': 'ASSOCIAÇÃO PEQUENOS PRODUTORES RURAIS ENGENHO JUSSARA',
    'BONAN�A PRODUTOS ALIMENT�CIOS E CESTAS B�SICAS EIRELI - EPP': 'BONANÇA PRODUTOS ALIMENTÍCIOS E CESTAS BÁSICAS EIRELI - EPP',
    'ASSOCIA??O PEQUENOS PRODUTORES RURAIS ENGENHO JUSSARA': 'ASSOCIAÇÃO PEQUENOS PRODUTORES RURAIS ENGENHO JUSSARA',
    'CJ CONSTRU��ES E EMPREENDIMENTOS EIRELI EPP': 'CJ CONSTRUÇÕES E EMPREENDIMENTOS EIRELI EPP',
    'GMAQ ALUGUEL DE M�QUINAS E SERVI�OS LTDA': 'GMAQ ALUGUEL DE MÁQUINAS E SERVIÇOS LTDA',
    'R�MULO LUIZ SANTANA DA SILVA ( J. NETO PRODUTOS   SERVI�OS)': 'RÔMULO LUIZ SANTANA DA SILVA ( J. NETO PRODUTOS   SERVIÇOS)',
    'THS CONSTRUTORA E INCORPORA��O LTDA - ME': 'THS CONSTRUTORA E INCORPORAÇÃO LTDA - ME',
    'TRIBUNAL DE JUSTI�A DO ESTADO DE PERNAMBUCO': 'TRIBUNAL DE JUSTIÇA DO ESTADO DE PERNAMBUCO',
    'FERNANDO JOS� DA SILVA': 'FERNANDO JOSÉ DA SILVA',
    'LUCIANE MARIA ANT?O DOS SANTOS81978600410': 'LUCIANE MARIA ANTÃO DOS SANTOS 81978600410',
    'JOABE LOPES DE FRAN?A': 'JOABE LOPES DE FRANÇA',
    'JAERSON LOPES DE FRAN?A': 'JAERSON LOPES DE FRANÇA',
    'CONS?RCIO DE TRANSP. DA REGI?O METROP. DO RECIFE LTDA': 'CONSÓRCIO DE TRANSP. DA REGIÃO METROP. DO RECIFE LTDA',
    'COMPANHIA ENERG?TICA DE PERNAMBUCO - CELPE': 'COMPANHIA ENERGÉTICA DE PERNAMBUCO - CELPE',
    'CENTRO DE INTEGRA??O EMPRESA ESCOLA DE PERNAMBUCO - CIEE': 'CENTRO DE INTEGRAÇÃO EMPRESA ESCOLA DE PERNAMBUCO - CIEE',
    'BONAN?A GAS EIRELI': 'BONANÇA GÁS EIRELI',
    'JOSEVALTER JOS� DE FRAN�A': 'JOSEVALTER JOSÉ DE FRANÇA',
    'UBERL�NDIA SILVA DE SOUZA': 'UBERLÂNDIA SILVA DE SOUZA',
    'MARIA JOS� NUNES VIEIRA': 'MARIA JOSÉ NUNES VIEIRA',
    'SEVERINO LOREN�O DA SILVA': 'SEVERINO LORENÇO DA SILVA',
    'ANA CAROLINE ARA�JO CAMPOS': 'ANA CAROLINE ARAÚJO CAMPOS',
    'ANAL�CIA FERREIRA DE MOURA BRAZ': 'ANALÍCIA FERREIRA DE MOURA BRAZ',
    'MARIA L�CIA DA SILVA': 'MARIA LÚCIA DA SILVA',
    'JOSE BARBOSA ANDR�': 'JOSE BARBOSA ANDRÉ',
    'JOS� AUGUSTO DIAS DA SILVA': 'JOSÉ AUGUSTO DIAS DA SILVA',
    'CAIXA ECON�MICA FEDERAL': 'CAIXA ECONÔMICA FEDERAL',
    'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCA��O': 'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCAÇÃO',
    'TELEF�NICA BRASIL S.A.': 'TELEFÔNICA BRASIL S.A.',
    'SERVI�O NACIONAL DE APRENDIZAGEM COMERCIAL - SENAC': 'SERVIÇO NACIONAL DE APRENDIZAGEM COMERCIAL - SENAC',
    'ESFERA PRESTA��O DE SERVI�OS E COM�RCIO LTDA': 'ESFERA PRESTAÇÃO DE SERVIÇOS E COMÉRCIO LTDA',
    'DAGEAL - COM�RCIO DE MATERIAL DE ESCRITORIO LTDA': 'DAGEAL - COMÉRCIO DE MATERIAL DE ESCRITÓRIO LTDA',
    'MJ COMERCIO DE M�VEIS EIRELI': 'MJ COMERCIO DE MÓVEIS EIRELI',
    'CONS�RCIO DE TRANSP. DA REGI�O METROP. DO RECIFE LTDA': 'CONSÓRCIO DE TRANSP. DA REGIÃO METROP. DO RECIFE LTDA',
    'JR-PARTNER INFORM�TICA LOCA��O E EVENTOS LTDA - ME': 'JR-PARTNER INFORMÁTICA LOCAÇÃO E EVENTOS LTDA - ME',
    'COMPANHIA ENERG�TICA DE PERNAMBUCO - CELPE': 'COMPANHIA ENERGÉTICA DE PERNAMBUCO - CELPE',
    'CENTRO DE INTEGRA��O EMPRESA ESCOLA DE PERNAMBUCO - CIEE': 'CENTRO DE INTEGRAÇÃO EMPRESA ESCOLA DE PERNAMBUCO - CIEE',
    'CIDADE EVANGELICA DOS ORF�OS': 'CIDADE EVANGÉLICA DOS ÓRFÃOS',
    'PONTESTUR AG�NCIA DE VIAGENS E TURISMO LTDA': 'PONTESTUR AGÊNCIA DE VIAGENS E TURISMO LTDA',
    '1 TELECOM SERVI�OS DE TECNOLOGIA EM INTERNET LTDA': '1 TELECOM SERVIÇOS DE TECNOLOGIA EM INTERNET LTDA',
    'UNDIME- UNI�O NACIONAL DOS DIRIGENTES MUNICIPAIS DE EDUCA': 'UNDIME- UNIÃO NACIONAL DOS DIRIGENTES MUNICIPAIS DE EDUCAÇÃO',
    'MP3 DISTRIBUI��O E IMPORTA��O DE UTILIDADES E MATERIAL ESCOLAR EIRELI - EPP': 'MP3 DISTRIBUIÇÃO E IMPORTAÇÃO DE UTILIDADES E MATERIAL ESCOLAR EIRELI - EPP',
    'UNI�O NACIONAL DOS CONSELHOS MUNICIPAIS DE EDUCA��O': 'UNIÃO NACIONAL DOS CONSELHOS MUNICIPAIS DE EDUCAÇÃO',
    'BONAN�A GAS EIRELI': 'BONANÇA GÁS EIRELI',
    'P. MESQUITA NETO DISTRIBUI��O DE �GUA': 'P. MESQUITA NETO DISTRIBUIÇÃO DE ÁGUA',
    'CONSULT SA�DE AMBIENTAL LTDA': 'CONSULT SAÚDE AMBIENTAL LTDA',
    'PESSOAL CIVIL SECRETARIA MUNICIPAL DE EDUCA��O': 'PESSOAL CIVIL SECRETARIA MUNICIPAL DE EDUCAÇÃO',
    'TRIBUNAL DE JUSTI�A DE PERNAMBUCO': 'TRIBUNAL DE JUSTIÇA DE PERNAMBUCO',
    'SYSTEMA INFORMATICA COMERCIO E SERVI�OS LTDA': 'SYSTEMA INFORMÁTICA COMÉRCIO E SERVIÇOS LTDA',
    'CELPE - COMPANHIA ENERG�TICA DE PERNAMBUCO': 'CELPE - COMPANHIA ENERGÉTICA DE PERNAMBUCO',
    'JOS� CARLOS DA SILVA CHAVEIRO - ME': 'JOSÉ CARLOS DA SILVA CHAVEIRO - ME',
    'VCOATSS COM�RCIO DE G�S E �GUA EIRELI': 'VCOATSS COMÉRCIO DE GÁS E ÁGUA EIRELI',
    'LU�S HENRIQUE A. DE MELO E SILVA - ME': 'LUÍS HENRIQUE A. DE MELO E SILVA - ME',
    'AR 19 CERTIFICA��O DIGITAL SERVI�OS LTDA': 'AR 19 CERTIFICAÇÃO DIGITAL SERVIÇOS LTDA',
    'ASSOCIA��O COMERCIAL E INDUSTRIAL DO LIMOEIRO': 'ASSOCIAÇÃO COMERCIAL E INDUSTRIAL DO LIMOEIRO',
    'LIMOPREV - FUNDO PREVIDENCI�RIO DO MUNIC�PIO DE LIMOEIRO': 'LIMOPREV - FUNDO PREVIDENCIÁRIO DO MUNICÍPIO DE LIMOEIRO',
    'EDV�NIA SABINO DE OLIVEIRA LUNA': 'EDVÂNIA SABINO DE OLIVEIRA LUNA',
    'F�BIA TACIANA C�NDIDA MARINHO': 'FÁBIA TACIANA CÂNDIDA MARINHO',
    'SELMA MARIA DE ARRUDA FRAN�A': 'SELMA MARIA DE ARRUDA FRANÇA',
    'JO�O GOMES DA SILVA': 'JOÃO GOMES DA SILVA',
    'ADAUTO ANT�NIO DE SOUSA FILHO': 'ADAUTO ANTÔNIO DE SOUSA FILHO',
    'MARIA AUXILIADORA ALVES ARAG�O': 'MARIA AUXILIADORA ALVES ARAGÃO',
    'TAMIRIS DA CONCEI��O DA SILVA': 'TAMIRIS DA CONCEIÇÃO DA SILVA',
    'JOS� ABEL CRISTOV�O DOS SANTOS': 'JOSÉ ABEL CRISTÓVÃO DOS SANTOS',
    'JOS� ERNANDES DE OLIVEIRA ARAG�O': 'JOSÉ ERNANDES DE OLIVEIRA ARAGÃO',
    'JOS� IVALDO DE ALBUQUERQUE CAVALCANTI': 'JOSÉ IVALDO DE ALBUQUERQUE CAVALCANTI',
    'MARIA L�CIA DE ALBUQUERQUE RODRIGUES': 'MARIA LÚCIA DE ALBUQUERQUE RODRIGUES',
    'DIORGENES JOS� DA SILVA': 'DIORGENES JOSÉ DA SILVA',
    'SAUL JOS� DE LUNA': 'SAUL JOSÉ DE LUNA',
    'KELLY KRISTINE CORREIA DE ARA�JO': 'KELLY KRISTINE CORREIA DE ARAÚJO',
    'MARIA BET�NIA DA SILVA': 'MARIA BETÂNIA DA SILVA',
    'SOCORRO EUFR�SIO DANTAS MENDES': 'SOCORRO EUFRÁSIO DANTAS MENDES',
    'LUIS GON�ALVES DO NASCIMENTO': 'LUIS GONÇALVES DO NASCIMENTO',
    'JOSEFA MARIA DA CONCEI��O': 'JOSEFA MARIA DA CONCEIÇÃO',
    'JOS� FERNANDO DE MELO': 'JOSÉ FERNANDO DE MELO',
    'JOS� FABIANO DE MELO SILVINO': 'JOSÉ FABIANO DE MELO SILVINO',
    'SEBASTI�O DE ABREU SILVA': 'SEBASTIÃO DE ABREU SILVA',
    'GERNAN DO REGO BIONE J�NIOR': 'GERNAN DO REGO BIONE JÚNIOR',
    'ANT�NIO SOARES CORREIA DE AZEVEDO': 'ANTÔNIO SOARES CORREIA DE AZEVEDO',
    'DANIELE MARIA FERREIRA LOUREN�O DE ARA�JO': 'DANIELE MARIA FERREIRA LOURENÇO DE ARAÚJO',
    'M�NICA MARIA DE LUCENA NEGROMONTE ROCHA': 'MÔNICA MARIA DE LUCENA NEGROMONTE ROCHA',
    'JOS� F�BIO CORREIA DE MELO': 'JOSÉ FÁBIO CORREIA DE MELO',
    'VALQU�RIA PINTO LEITE': 'VALQUÉRIA PINTO LEITE',
    'FLOR DA MATA COMERCIO EMPREENDIMENTOS E SERVI�OS EIRELI': 'FLOR DA MATA COMERCIO EMPREENDIMENTOS E SERVIÇOS EIRELI',
    'IAUPE - INSTITUTO DE APOIO A FUNDA��O UNIVERSIDADE DE PERNAMBUCO': 'IAUPE - INSTITUTO DE APOIO A FUNDAÇÃO UNIVERSIDADE DE PERNAMBUCO',
    'UNI�O NACIONAL DOS DIRIGENTES MUNICIPAIS DE EDUCA��O': 'UNIÃO NACIONAL DOS DIRIGENTES MUNICIPAIS DE EDUCAÇÃO',
    'A. M. DE SOUZA ARAG�O': 'A. M. DE SOUZA ARAGÃO',
    'JAIRTON SILVA OLIVEIRA INFORM�TICA': 'JAIRTON SILVA OLIVEIRA INFORMÁTICA',
    'DAGEAL - COMERCIO DE MATERIAL DE ESCRIT�RIO LTDA': 'DAGEAL - COMERCIO DE MATERIAL DE ESCRITÓRIO LTDA',
    'DETRAN - DEPARTAMENTO ESTADUAL DE TR�NSITO DE PERNAMBUCO': 'DETRAN - DEPARTAMENTO ESTADUAL DE TRÂNSITO DE PERNAMBUCO',
    'ASSOCIA��O ATL�TICA BANCO DO BRASIL': 'ASSOCIAÇÃO ATLÉTICA BANCO DO BRASIL',
    'CART�RIO 2� OF�CIO DE REGISTRO DE T�TULOS E DOCUMENTOS DE REG. CIVIL DE PESSOAS': 'CARTÓRIO 2º OFÍCIO DE REGISTRO DE TÍTULOS E DOCUMENTOS DE REG. CIVIL DE PESSOAS',
    'DIOCESE DE NAZAR�': 'DIOCESE DE NAZARÉ',
    'CENTRO DE CRIA��O GALP�O DAS ARTES': 'CENTRO DE CRIAÇÃO GALPÃO DAS ARTES',
    'CART�RIO DE LIMOEIRO - PE - 2 OF�CIO': 'CARTÓRIO DE LIMOEIRO - PE - 2 OFÍCIO',
    'ASSOCIA��O FRANCISCANA MARISTELA DO BRASIL': 'ASSOCIAÇÃO FRANCISCANA MARISTELA DO BRASIL',
    'FEDERA��O PERNAMBUCANA DE FUTEBOL DE SAL�O': 'FEDERAÇÃO PERNAMBUCANA DE FUTEBOL DE SALÃO',
    'UNI�O DOS DIRIGENTES MUNICIPAIS DE EDUCA��O': 'UNIÃO DOS DIRIGENTES MUNICIPAIS DE EDUCAÇÃO',
    'VANESSA ALBUQUERQUE GON�ALVES COSTA ME': 'VANESSA ALBUQUERQUE GONÇALVES COSTA ME',
    'JUME�S MATERIAL DE CONSTRU��O LTDA': 'JUMES MATERIAL DE CONSTRUÇÃO LTDA',
    'JOS� SINALDO SOUZA DA SILVA': 'JOSÉ SINALDO SOUZA DA SILVA',
    'MORK SOLAR - PRODUTOS E SERVI�OS EL�TRICOS LTDA': 'MORK SOLAR - PRODUTOS E SERVIÇOS ELÉTRICOS LTDA',
    'ALIAN�A DISTRIBUIDORA DE MATERIAI EM GERAL LTDA - ME': 'ALIANÇA DISTRIBUIDORA DE MATERIAIS EM GERAL LTDA - ME',
    'NO� DA SILVA MENDONCA 68770472491': 'NOÉ DA SILVA MENDONÇA 68770472491',
    'GRAFICPAPER COM�RCIO E SERVI�OS EIRELI': 'GRAFICPAPER COMÉRCIO E SERVIÇOS EIRELI',
    'ALBA VAL�RIA ANDRADE SILVA ME': 'ALBA VALÉRIA ANDRADE SILVA ME',
    'A. R. CONFEC��ES DE ROUPAS E FARDAMENTOS LTDA': 'A. R. CONFECÇÕES DE ROUPAS E FARDAMENTOS LTDA',
    'FUNDO MUNICIPAL DE EDUCA��O - FME': 'FUNDO MUNICIPAL DE EDUCAÇÃO - FME',
    'MILKMA COMERCIO E SERVI�OS LTDA ME': 'MILKMA COMERCIO E SERVIÇOS LTDA ME',
    'SANTOS   SILVA ASSESSORIA P�BLICA LTDA': 'SANTOS   SILVA ASSESSORIA PÚBLICA LTDA',
    '�NICA SANEANTES LTDA': 'ÚNICA SANEANTES LTDA',
    'IMPERIO EMPREENDIMENTOS COMERCIAIS E SERVI�OS LTDA': 'IMPERIO EMPREENDIMENTOS COMERCIAIS E SERVIÇOS LTDA',
    'SANDRA VAL�RIA DE ARRUDA SANTOS': 'SANDRA VALÉRIA DE ARRUDA SANTOS',
    '�RICA PATR�CIA DA SIVLA AMORIM': 'ÉRICA PATRÍCIA DA SILVA AMORIM',
    'MARIA DA CONCEI��O AMORIM DE AZEVEDO': 'MARIA DA CONCEIÇÃO AMORIM DE AZEVEDO',
    'JOS� FERNANDO DA SILVA ALVES': 'JOSÉ FERNANDO DA SILVA ALVES',
    'CASSIA MIRTHYS GON�ALVES DE MOURA R�GO': 'CASSIA MIRTHYS GONÇALVES DE MOURA RÊGO',
    'MARIA LUIZA SIM�ES': 'MARIA LUIZA SIMÕES',
    'MARIA DA CONCEI��O DE MELO SILVA': 'MARIA DA CONCEIÇÃO DE MELO SILVA',
    'MARIA JOS� GOMES DA SILVA PRADO': 'MARIA JOSÉ GOMES DA SILVA PRADO',
    'BRENA VAL�RIA DE AZEVEDO EVANGELISTA': 'BRENA VALÉRIA DE AZEVEDO EVANGELISTA',
    'THIAGO JOS� CARVALHO BARBOSA': 'THIAGO JOSÉ CARVALHO BARBOSA',
    'GE�RGIO DE SANTANA GUEDES': 'GEÓRGIO DE SANTANA GUEDES',
    'ANA L�CIA RAMOS DE AMORIM ARAG�O': 'ANA LÚCIA RAMOS DE AMORIM ARAGÃO',
    'VITAL E VITOR MATERIAL DE CONSTRU��O LTDA': 'VITAL E VITOR MATERIAL DE CONSTRUÇÃO LTDA',
    'RODRIGO DE L. SILVA COM�RCIO PE�AS E ACESS�RIOS': 'RODRIGO DE L. SILVA COMÉRCIO PEÇAS E ACESSÓRIOS',
    'DIVINA FAC��O LTDA': 'DIVINA FACÇÃO LTDA',
    'C?TIA CARNEIRO DA SILVA FIGUEIREDO': 'CÁTIA CARNEIRO DA SILVA FIGUEIREDO',
    'Magda Alexandra Alves da Fons?ca': 'MAGDA ALEXANDRA ALVES DA FONSECA',
    'ELIZ?NGELA DA SILVA COSTA': 'ELIZÂNGELA DA SILVA COSTA',
    'L�VIA MARIA DA SILVA SOUZA': 'LÍVIA MARIA DA SILVA SOUZA',
    'EROTIDES CAROLINE EST�V�O DE ARRUDA': 'EROTIDES CAROLINE ESTÊVÃO DE ARRUDA',
    'MARIA DE F�TIMA TAVARES DA SILVA': 'MARIA DE FÁTIMA TAVARES DA SILVA',
    'VIRG�NIA RUFINO DE ALBUQUERQUE': 'VIRGÍNIA RUFINO DE ALBUQUERQUE',
    'RITA DE C�SSIA PEREIRA DA SILVA': 'RITA DE CÁSSIA PEREIRA DA SILVA',
    'F�BIA VER�NICA DA SILVA': 'FÁBIA VERÔNICA DA SILVA',
    'J�SSICA PRISCILA SILVA CHAVES': 'JÉSSICA PRISCILA SILVA CHAVES',
    'FAGNA GOMES DE ARA�JO': 'FAGNA GOMES DE ARAÚJO',
    'ANA CL�UDIA DE A. SANTOS CRUZ': 'ANA CLÁUDIA DE A. SANTOS CRUZ',
    'MARIA RITA DE C�SSIA DE L. SANTOS': 'MARIA RITA DE CÁSSIA DE L. SANTOS',
    'CL�UDIA PATR�CIA DE OLIVEIRA RODRIGUES': 'CLÁUDIA PATRÍCIA DE OLIVEIRA RODRIGUES',
    'ELIS�NGELA KELLY O. DE MOURA ANICETO': 'ELISÂNGELA KELLY O. DE MOURA ANICETO',
    'MARIA SILV�NIA DE MOURA': 'MARIA SILVÂNIA DE MOURA',
    'ANA CL�UDIA GOMES DE SOUSA DIAS': 'ANA CLÁUDIA GOMES DE SOUSA DIAS',
    'ANA ALICE DA SILVA F�LIX': 'ANA ALICE DA SILVA FÉLIX',
    'MARIA JOS� SOARES DA SILVA': 'MARIA JOSÉ SOARES DA SILVA',
    'IARA CAROLINE DA SILVA ARA�JO': 'IARA CAROLINE DA SILVA ARAÚJO',
    'VALD�NIA PESSOA DE FARIAS FERREIRA': 'VALDÊNIA PESSOA DE FARIAS FERREIRA',
    'LA�S CAROLANE DA SILVA SOUZA': 'LAÍS CAROLANE DA SILVA SOUZA',
    'MARIA JOS� GUILHERME DA SILVA ALVES': 'MARIA JOSÉ GUILHERME DA SILVA ALVES',
    'LET�CIA VIT�RIA DA SILVA': 'LETÍCIA VITÓRIA DA SILVA',
    'ANDR�IA DE ARA�JO FERREIRA': 'ANDRÉIA DE ARAÚJO FERREIRA',
    'TAMIRES TAVARES DE ARRUDA BUR�GIO': 'TAMIRES TAVARES DE ARRUDA BURÉGIO',
    'MAR�LIA GABRIELA FIGUEIREDO DA SILVA': 'MARÍLIA GABRIELA FIGUEIREDO DA SILVA',
    'MARIA BET�NIA DO NASCIMENTO': 'MARIA BETÂNIA DO NASCIMENTO',
    'JAMANDA TAMIRES TEN�RIO SANTANA': 'JAMANDA TAMIRES TENÓRIO SANTANA',
    'MARIA BET�NIA RIBEIRO DE SOUZA': 'MARIA BETÂNIA RIBEIRO DE SOUZA',
    'SUELY DE ARA�JO PEREIRA LOPES': 'SUELY DE ARAÚJO PEREIRA LOPES',
    'CRISTIANE ARA�JO SANTANA GOMES': 'CRISTIANE ARAÚJO SANTANA GOMES',
    'C�SSIA NAIARA DE LIMA SANTOS': 'CÁSSIA NAIARA DE LIMA SANTOS',
    'ANA PATR�CIA OLIVEIRA SILVA': 'ANA PATRÍCIA OLIVEIRA SILVA',
    'BRUNA RAFAELE DE ARA�JO BEZERRA': 'BRUNA RAFAELE DE ARAÚJO BEZERRA',
    'C�SSIA MIRELLE DA SILVA OLIVEIRA': 'CÁSSIA MIRELLE DA SILVA OLIVEIRA',
    'LUCIANE DE SANTANA HER�NCIO': 'LUCIANE DE SANTANA HERÊNCIO',
    'MARIA JOS� DA SILVA AZEVEDO': 'MARIA JOSÉ DA SILVA AZEVEDO',
    'M�NICA VAL�RIA DE BARROS AQUINO': 'MÔNICA VALÉRIA DE BARROS AQUINO',
    'P�MELLA CAMILY PEREIRA DOS SANTOS': 'PÂMELLA CAMILY PEREIRA DOS SANTOS',
    'ANNE RAFAELE FIGUER�DO DA SILVA': 'ANNE RAFAELE FIGUERÊDO DA SILVA',
    'VERAL�CIA RIBEIRO DOS S. MOURA': 'VERALÚCIA RIBEIRO DOS S. MOURA',
    'MARIA DE F�TIMA DA SILVA': 'MARIA DE FÁTIMA DA SILVA',
    'JULIANA VIT�RIA DE MOURA BERNARDINO': 'JULIANA VITÓRIA DE MOURA BERNARDINO',
    'J�SSICA GOMES DE LUNA': 'JÉSSICA GOMES DE LUNA',
    'CINTIA GOMES DE ABREU AZEV�DO': 'CINTIA GOMES DE ABREU AZEVÊDO',
    'ROM�NIA BELO DA SILVA': 'ROMÊNIA BELO DA SILVA',
    'NATALICIA GON�ALVES DE MOURA': 'NATALICIA GONÇALVES DE MOURA',
    'AYANE STEFANE LOUREN�O MARQUES': 'AYANE STEFANE LOURENÇO MARQUES',
    'ROG�RIA DO NASCIMENTO ALBUQUERQUE': 'ROGÉRIA DO NASCIMENTO ALBUQUERQUE',
    'DAYENE STHEFANNY MENDON�A SOUSA': 'DAYENE STHEFANNY MENDONÇA SOUSA',
    'ELIDA TAINARA DA SILVA MENDON�A': 'ELIDA TAINARA DA SILVA MENDONÇA',
    'ANA LET�CIA BARBOSA DE AMORIM': 'ANA LETÍCIA BARBOSA DE AMORIM',
    'AMANDA TAMIRES TEN�RIO SANTANA': 'AMANDA TAMIRES TENÓRIO SANTANA',
    'MARIA JOS� FELIPE NETO': 'MARIA JOSÉ FELIPE NETO',
    'LUANA LET�CIA SOUSA DE OLIVEIRA': 'LUANA LETÍCIA SOUSA DE OLIVEIRA',
    'LEILA CAVALCANTI DE ARA�JO': 'LEILA CAVALCANTI DE ARAÚJO',
    'Magda Alexandra Alves da Fons�ca': 'MAGDA ALEXANDRA ALVES DA FONSECA',
    'INDUSTRIA E COM�RCIO DE M�VEIS KUTZ LTDA': 'INDUSTRIA E COMÉRCIO DE MÓVEIS KUTZ LTDA',
    'D. FEITOSA ALUGUEL DE M�QUINAS E EQUIPAMENTO PARA CONSTRU��O EIRELI': 'D. FEITOSA ALUGUEL DE MÁQUINAS E EQUIPAMENTO PARA CONSTRUÇÃO EIRELI',
    'THALIA ARIADNE PE�A ARAG�O': 'THALIA ARIADNE PEÑA ARAGÃO',
    'LE�NIDAS CARLOS SANTOS DE ALBUQUERQUE': 'LEÔNIDAS CARLOS SANTOS DE ALBUQUERQUE',
    'GUSTAVO HENRIQUE DE ARAG�O FERREIRA': 'GUSTAVO HENRIQUE DE ARAGÃO FERREIRA',
    'QUALINFO SERVI�OS DE INFORMATICA LTDA EPP': 'QUALINFO SERVIÇOS DE INFORMATICA LTDA EPP',
    'HOSTAZUL / MW �GIL': 'HOSTAZUL / MW ÁGIL',
    'WELLEYSON C�SAR DA SILVA': 'WELLEYSON CÉSAR DA SILVA',
    'JO�O MARTINS DE ATHAYDE J�NIOR - ME': 'JOÃO MARTINS DE ATHAYDE JÚNIOR - ME',
    'LINK CARD ADMINISTRADORA DE BENEF�CIOS EIRELI': 'LINK CARD ADMINISTRADORA DE BENEFÍCIOS EIRELI',
    'JOS� ANT�NIO DE AGUIAR': 'JOSÉ ANTÔNIO DE AGUIAR',
    'M. A. DE LIMA DISTRIBUI��O E SERVI�OS': 'M. A. DE LIMA DISTRIBUIÇÃO E SERVIÇOS',
    'ASSOCIA��O SANTO AGOSTINHO': 'ASSOCIAÇÃO SANTO AGOSTINHO',
    'ASSOCIA��O DOS AGRICULTORES RURAIS DO S�TIO QUECEQUE': 'ASSOCIAÇÃO DOS AGRICULTORES RURAIS DO SÍTIO QUECEQUE',
    'MIL COMERCIO DE MATERIAIS DE CONSTRU��O EIRELI': 'MIL COMERCIO DE MATERIAIS DE CONSTRUÇÃO EIRELI',
    'MARIA JOS� DA SILVA': 'MARIA JOSÉ DA SILVA',
    'VER�NICA ROCHA DE CARVALHO ATAIDE': 'VERÔNICA ROCHA DE CARVALHO ATAIDE',
    'LORHANY NAT�RCIA DE ABREU AZEVEDO': 'LORHANY NATÁRCIA DE ABREU AZEVEDO',
    'DIANA FRAN�A COSTA DA SILVA': 'DIANA FRANÇA COSTA DA SILVA',
    'LUCAS VIN�CIUS DE OLIVERIA ROCHA': 'LUCAS VINÍCIUS DE OLIVEIRA ROCHA',
    'ANA VAL�RIA DA CRUZ BARBOZA': 'ANA VALÉRIA DA CRUZ BARBOZA',
    'DAYANE FRAN�A COSTA DA SILVA': 'DAYANE FRANÇA COSTA DA SILVA',
    'LS SERVI�OS DE INFORM�TICA E ELETR�NICA LTDA EPP': 'LS SERVIÇOS DE INFORMÁTICA E ELETRÔNICA LTDA EPP',
    'CONSTR�I MATERIAIS DIVERSOS EIRELI ME': 'CONSTRÓI MATERIAIS DIVERSOS EIRELI ME'
}

df['FORNECEDOR'] = df['FORNECEDOR'].replace(mapa_fornecedor)

df['FORNECEDOR'].unique()

"""# **Download**

Area comentada, para baixar, apague
"""

from google.colab import files

# Salva em Excel
#df.to_excel('bd_tratado.xlsx', index=False)

# Faz o download
#files.download('bd_tratado.xlsx')

# Salva em JSON (orientação padrão)
df.to_json('bd_tratadoj.json', orient='records', force_ascii=False)

# Faz o download
files.download('bd_tratadoj.json')